<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3272c3b2b6d07a418f763affe740b41a
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3272c3b2b6d07a418f763affe740b41a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3272c3b2b6d07a418f763affe740b41a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
